//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolarInsalation
    {
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public Nullable<int> ETR { get; set; }
        public Nullable<int> ETRN { get; set; }
        public int Id { get; set; }
    }
}
