//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarStation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SolarPanelEntities : DbContext
    {
        public SolarPanelEntities()
            : base("name=SolarPanelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Solar_Panels> Solar_Panels { get; set; }
        public virtual DbSet<SolarInsalation> SolarInsalations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
